title: Paleo Data Hub
description: A clearinghouse for information about digitizing paleontology collections
theme: minimal-mistakes-jekyll
exclude: [scripts]

repository: adamancuer/geo-ose-mm

collections_dir: collections
collections:
  resources:
    output: True
    sort_by: nav_order