title: Paleo Data Hub
description: A clearinghouse for information about digitizing paleontology collections
repository: adamancer/geo-ose-mm
theme: minimal-mistakes-jekyll
exclude: [scripts, templates]

atom_feed:
  hide: true

after_footer_scripts:
  - /assets/js/custom.js

search: true
lunr:
  search_full_content: true
  search_within_pages: true

collections_dir: collections
collections:
  community:
    output: True
    sort_by: nav_order
  explanations:
    output: True
    sort_by: nav_order
  how_to_guides:
    output: True
    sort_by: nav_order
  paleo_data_ecosystem:
    output: True
    sort_by: nav_order
  tutorials:
    output: True
    sort_by: nav_order

defaults:
  - scope:
      path: ""
    values:
      layout: single
      sidebar:
        nav: sidebar
        collapsible: True
  - scope:
      path: collections
    values:
      toc: true
      toc_sticky: true
  - scope:
      path: ""
      type: community
    values:
      sidebar:
        expanded: [community]
  - scope:
      path: ""
      type: explanations
    values:
      sidebar:
        expanded: [explanations]
  - scope:
      path: ""
      type: how_to_guides
    values:
      sidebar:
        expanded: [how_to_guides]
  - scope:
      path: ""
      type: paleo_data_ecosystem
    values:
      sidebar:
        expanded: [paleo_data_ecosystem]
  - scope:
      path: ""
      type: tutorials
    values:
      sidebar:
        expanded: [tutorials]
