title: Paleo Data Hub
description: A clearinghouse for information about digitizing paleontology collections
repository: adamancer/geo-ose-mm
theme: minimal-mistakes-jekyll
exclude: [scripts, templates]

minimal_mistakes_skin: air
atom_feed:
  hide: true

search: true
lunr:
  search_full_content: true
  search_within_pages: true

collections_dir: collections
collections:
  howto:
    output: True
    sort_by: nav_order
  topics:
    output: True
    sort_by: nav_order

defaults:
  - 
    scope:
      path: ""
    values:
      layout: single
  -
    scope:
      path: collections
    values:
      classes: wide
      sidebar:
        nav: main
  -
    scope:
      path: collections/_tags
    values:
      sidebar:
        nav: tags
  
